// Code generated by logcopter-gen; DO NOT EDIT.

package cmd

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.go-go-mcp.cmd.apps.scholarly.cmd")
