// Code generated by logcopter-gen; DO NOT EDIT.

package tool_registry

import logcopter "github.com/go-go-golems/logcopter/pkg/logcopter"

var zlog = logcopter.Package("go-go-golems.go-go-mcp.pkg.tools.providers.tool-registry")
